import {
  Selector
} from 'testcafe';

import Page from './page.js'

const page = new Page();

export default class Links {
  constructor() {

    this.pageLinks = [
      this.abTesting = Selector('#content > ul > li:nth-child(1) > a'),
      this.addRemove = Selector('#content > ul > li:nth-child(2) > a'),
      this.basicAuth = Selector('#content > ul > li:nth-child(3) > a'),
      this.brokenImgs = Selector('#content > ul > li:nth-child(4) > a'),
      this.challengingDom = Selector('#content > ul > li:nth-child(5) > a'),
      this.checkboxes = Selector('#content > ul > li:nth-child(6) > a'),
      this.contextMenu = Selector('#content > ul > li:nth-child(7) > a'),
      this.digestAuth = Selector('#content > ul > li:nth-child(8) > a'),
      this.disappearElmts = Selector('#content > ul > li:nth-child(9) > a'),
      this.dragDrop = Selector('#content > ul > li:nth-child(10) > a'),
      this.dropdown = Selector('#content > ul > li:nth-child(11) > a'),
      this.dynContent = Selector('#content > ul > li:nth-child(12) > a'),
      this.dynControls = Selector('#content > ul > li:nth-child(13) > a'),
      this.dynLoading = Selector('#content > ul > li:nth-child(14) > a'),
      this.entryAd = Selector('#content > ul > li:nth-child(15) > a'),
      this.exitIntent = Selector('#content > ul > li:nth-child(16) > a'),
      this.fileDownload = Selector('#content > ul > li:nth-child(17) > a'),
      this.fileUpload = Selector('#content > ul > li:nth-child(18) > a'),
      this.floatingMenu = Selector('#content > ul > li:nth-child(19) > a'),
      this.forgotPword = Selector('#content > ul > li:nth-child(20) > a'),
      this.formAuth = Selector('#content > ul > li:nth-child(21) > a'),
      this.frames = Selector('#content > ul > li:nth-child(22) > a'),
      this.geolocation = Selector('#content > ul > li:nth-child(23) > a'),
      this.horizontalSlider = Selector('#content > ul > li:nth-child(24) > a'),
      this.hovers = Selector('#content > ul > li:nth-child(25) > a'),
      this.infiniteScroll = Selector('#content > ul > li:nth-child(26) > a'),
      this.inputs = Selector('#content > ul > li:nth-child(27) > a'),
      this.jqueryUIMenus = Selector('#content > ul > li:nth-child(28) > a'),
      this.jsAlerts = Selector('#content > ul > li:nth-child(29) > a'),
      this.jsOnloadEventError = Selector('#content > ul > li:nth-child(30) > a'),
      this.keyPresses = Selector('#content > ul > li:nth-child(31) > a'),
      this.largeDeepDom = Selector('#content > ul > li:nth-child(32) > a'),
      this.multWindows = Selector('#content > ul > li:nth-child(33) > a'),
      this.nestedFrames = Selector('#content > ul > li:nth-child(34) > a'),
      this.notificationMsgs = Selector('#content > ul > li:nth-child(35) > a'),
      this.redirectLink = Selector('#content > ul > li:nth-child(36) > a'),
      this.secureFileDload = Selector('#content > ul > li:nth-child(37) > a'),
      this.shiftingContent = Selector('#content > ul > li:nth-child(38) > a'),
      this.slowResources = Selector('#content > ul > li:nth-child(39) > a'),
      this.sortableDateTables = Selector('#content > ul > li:nth-child(40) > a'),
      this.statusCodes = Selector('#content > ul > li:nth-child(41) > a'),
      this.typos = Selector('#content > ul > li:nth-child(42) > a'),
      this.wysiwygEditor = Selector('#content > ul > li:nth-child(43) > a'),

    ]


    this.pageLinksText = [

      this.abTestingText = 'A/B Testing',
      this.addRemoveText = 'Add/Remove Elements',
      this.basicAuthText = 'Basic Auth',
      this.brokenImgsText = 'Broken Images',
      this.challengingDomText = 'Challenging DOM',
      this.checkboxesText = 'Checkboxes',
      this.contextMenuText = 'Context Menu',
      this.digestAuthText = 'Digest Authentication',
      this.disappearElmtsText = 'Disappearing Elements',
      this.dragDropText = 'Drag and Drop',
      this.dropdownText = 'Dropdown',
      this.dynContentText = 'Dynamic Content',
      this.dynControlsText = 'Dynamic Controls',
      this.dynLoadingText = 'Dynamic Loading',
      this.entryAdText = 'Entry Ad',
      this.exitIntentText = 'Exit Intent',
      this.fileDownloadText = 'File Download',
      this.fileUploadText = 'File Upload',
      this.floatingMenuText = 'Floating Menu',
      this.forgotPwordText = 'Forgot Password',
      this.formAuthText = 'Form Authentication',
      this.framesText = 'Frames',
      this.geolocationText = 'Geolocation',
      this.horizontalSliderText = 'Horizontal Slider',
      this.hoversText = 'Hovers',
      this.infiniteScrollText = 'Infinite Scroll',
      this.inputsText = 'Inputs',
      this.jqueryUIMenusText = 'JQuery UI Menus',
      this.jsAlertsText = 'JavaScript Alerts',
      this.jsOnloadEventErrorText = 'JavaScript onload event error',
      this.keyPressesText = 'Key Presses',
      this.largeDeepDomText = 'Large & Deep DOM',
      this.multWindowsText = 'Multiple Windows',
      this.nestedFramesText = 'Nested Frames',
      this.notificationMsgsText = 'Notification Messages',
      this.redirectLinkText = 'Redirect Link',
      this.secureFileDloadText = 'Secure File Download',
      this.shiftingContentText = 'Shifting Content',
      this.slowResourcesText = 'Slow Resources',
      this.sortableDateTablesText = 'Sortable Data Tables',
      this.statusCodesText = 'Status Codes',
      this.typosText = 'Typos',
      this.wysiwygEditorText = 'WYSIWYG Editor',

    ]

    this.pageLinksHref = [
          //page.basePageUrl + href      
      this.abTestingHref = '/abtest',
      this.addRemoveHref = '/add_remove_elements/',
      this.basicAuthHref = '/basic_auth',
      this.brokenImgsHref = '/broken_images',
      this.challengingDomHref = '/challenging_dom',
      this.checkboxesHref = '/checkboxes',
      this.conHrefMenuHref = '/context_menu',
      this.digestAuthHref = '/digest_auth',
      this.disappearElmtsHref = '/disappearing_elements',
      this.dragDropHref = '/drag_and_drop',
      this.dropdownHref = '/dropdown',
      this.dynContentHref = '/dynamic_content',
      this.dynControlsHref = '/dynamic_controls',
      this.dynLoadingHref = '/dynamic_loading',
      this.entryAdHref = '/entry_ad',
      this.exitIntentHref = '/exit_intent',
      this.fileDownloadHref = '/download',
      this.fileUploadHref = '/upload',
      this.floatingMenuHref = '/floating_menu',
      this.forgotPwordHref = '/forgot_password',
      this.formAuthHref = '/login',
      this.framesHref = '/frames',
      this.geolocationHref = '/geolocation',
      this.horizontalSliderHref = '/horizontal_slider',
      this.hoversHref = '/hovers',
      this.infiniteScrollHref = '/infinite_scroll',
      this.inputsHref = '/inputs',
      this.jqueryUIMenusHref = '/jqueryui/menu',
      this.jsAlertsHref = '/javascript_alerts',
      this.jsOnloadEventErrorHref = '/javascript_error',
      this.keyPressesHref = '/key_presses',
      this.largeDeepDomHref = '/large',
      this.multWindowsHref = '/windows',
      this.nestedFramesHref = '/nested_frames',
      this.notificationMsgsHref = '/notification_message_rendered',
      this.redirectLinkHref = '/redirector',
      this.secureFileDloadHref = '/download_secure',
      this.shiftingContentHref = '/shifting_content',
      this.slowResourcesHref = '/slow',
      this.sortableDateTablesHref = '/tables',
      this.statusCodesHref = '/status_codes',
      this.typosHref = '/typos',
      this.wysiwygEditorHref = '/tinymce',
    ]

  }
}
